### ISSUE TITLE
Add github actions

### ISSUE THREAD

**Issue by thrilok209** [InstaDApp/dsa-connect#28]
Add Github actions for publishing a new version of SDK to npm.

**Comment by ishanjain28** [comment]
@thrilok209 Hey, I am testing this locally right now. Can we fix the tests in this repo first?
Right now, I have configured it to run `npm ci && npm run test` before publishing the package.. And some tests are failing.

**Comment by thrilok209** [comment]
> @thrilok209 Hey, I am testing this locally right now. Can we fix the tests in this repo first?
> Right now, I have configured it to run `npm ci && npm run test` before publishing the package.. And some tests are failing.

Sure. I will fix the tests.

**Comment by thrilok209** [comment]
@ishanjain28 Fixed it.
